uploading codecov on every env, write to console if codecov update failed, add check for surefire folder, build

diff --git a/appveyor.yml b/appveyor.yml
--- a/appveyor.yml
+++ b/appveyor.yml
@@ -73,8 +73,9 @@ for:
       
     on_finish:
       - ps: $wc = New-Object 'System.Net.WebClient';
+          if(Test-Path -Path $env:APPVEYOR_BUILD_FOLDER/target/surefire-reports) { `
             foreach($file in get-childItem $env:APPVEYOR_BUILD_FOLDER/target/surefire-reports -include TEST-*.xml -name) { `
-              $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\target\surefire-reports\$file)); }
+              $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$env:APPVEYOR_JOB_ID", (Resolve-Path .\target\surefire-reports\$file)); }}
       - ps: $wc = New-Object 'System.Net.WebClient';
           if(Test-Path -Path $env:APPVEYOR_BUILD_FOLDER/target/failsafe-reports) { `
             foreach($file in get-childItem $env:APPVEYOR_BUILD_FOLDER/target/failsafe-reports -include TEST-*.xml -name) { `
@@ -82,8 +83,9 @@ for:
 
     on_failure:
       - ps: $wc = New-Object 'System.Net.WebClient';
-          foreach($file in get-childItem $env:APPVEYOR_BUILD_FOLDER/target/surefire-reports -include *.txt -name) { `
-            Push-AppveyorArtifact (Resolve-Path .\target\surefire-reports\$file); }
+          if(Test-Path -Path $env:APPVEYOR_BUILD_FOLDER/target/surefire-reports) { `
+            foreach($file in get-childItem $env:APPVEYOR_BUILD_FOLDER/target/surefire-reports -include *.txt -name) { `
+              Push-AppveyorArtifact (Resolve-Path .\target\surefire-reports\$file); }}
       - ps: $wc = New-Object 'System.Net.WebClient';
           if(Test-Path -Path $env:APPVEYOR_BUILD_FOLDER/target/failsafe-reports) { `
             foreach($file in get-childItem $env:APPVEYOR_BUILD_FOLDER/target/failsafe-reports -include *.txt -name) { `
@@ -91,7 +93,7 @@ for:
 
     on_success:
       - ps: Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe; 
-            .\codecov.exe -t $CODECOV_TOKEN -f $APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged/jacoco.xml
+            .\codecov.exe -t $CODECOV_TOKEN -f $APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged/jacoco.xml || Write-Host "Failed to post Windows codecov"
 
     cache:
       - '%MAVEN_HOME% -> pom.xml'
@@ -117,20 +119,20 @@ for:
 
     on_finish:
       - sh: |
-          find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
+          if [ -d "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"; fi
       - sh: |
           if [ -d "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"; fi
 
     on_failure:
       - sh: |
-          find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name '*.txt' -print0 | xargs -0 -I '{}' appveyor PushArtifact -Path '{}'
+          if [ -d "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name '*.txt' -print0 | xargs -0 -I '{}' appveyor PushArtifact -Path '{}'; fi
       - sh: |
           if [ -d "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" -type f -name '*.txt' -print0 | xargs -0 -I '{}' appveyor PushArtifact -Path '{}'; fi
 
     on_success:
       - sh: curl -Os https://uploader.codecov.io/latest/linux/codecov &&
           chmod +x codecov &&
-          ./codecov -t $CODECOV_TOKEN -f $APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged/jacoco.xml
+          ./codecov -t $CODECOV_TOKEN -f $APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged/jacoco.xml || echo "Failed to post Linux codecov"
 
     cache:
       - $HOME/.m2 -> pom.xml
@@ -155,15 +157,20 @@ for:
 
     on_finish:
       - sh: |
-          find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"
+          if [ -d "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"; fi
       - sh: |
           if [ -d "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" -type f -name 'TEST-*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID"; fi
 
     on_failure:
       - sh: |
-          find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name '*.txt' -print0 | xargs -0 -I '{}' appveyor PushArtifact -Path '{}'
+          if [ -d "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/surefire-reports" -type f -name '*.txt' -print0 | xargs -0 -I '{}' appveyor PushArtifact -Path '{}'; fi
       - sh: |
           if [ -d "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" ]; then find "$APPVEYOR_BUILD_FOLDER/target/failsafe-reports" -type f -name '*.txt' -print0 | xargs -0 -I '{}' appveyor PushArtifact -Path '{}'; fi
+
+    on_success:
+      - sh: curl -Os https://uploader.codecov.io/latest/macos/codecov &&
+          chmod +x codecov &&
+          ./codecov -t $CODECOV_TOKEN -f $APPVEYOR_BUILD_FOLDER/target/site/jacoco-merged/jacoco.xml || echo "Failed to post Mac codecov"
 
     cache:
       - $HOME/.m2 -> pom.xml
